2020-03-22:  version 0.3.7\n   - added: user confirmation to post purge script\n\n

diff --git a/contrib/DEBIAN/postrm b/contrib/DEBIAN/postrm
--- a/contrib/DEBIAN/postrm
+++ b/contrib/DEBIAN/postrm
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr//bin/env bash
+#
 # postrm script for p4d
 #
-# see: dh_installdeb(1)
 
 set -e
 
@@ -21,24 +21,25 @@ set -e
 
 case "$1" in
     purge)
-#        echo -n "Drop the p4 database and collected data? [y/N] "
-#        echo ""
-#        read -n 1 c
+        echo -n "Drop the p4 database (collected data will be lost and should be backuped manually before)? [y/N] "
+        echo ""
+        read -n 1 c
+        echo ""
 
-#        if [ "${c}" == "y" ]; then
+        if [ "${c}" == "y" ]; then
             echo "drop database p4;" | mysql -u root -Dmysql
             echo "drop user p4@localhost;" | mysql -u root -Dmysql
             echo "database droped!"
-#        else
-#            echo "droping database aborted!"
-#        fi
+        else
+            echo "droping database aborted!"
+        fi
         ;;
 
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
         ;;
 
     *)
-        echo "postrm called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument '$1'" >&2
         exit 1
         ;;
 esac
